In [37]:
import tensorflow as tf

from keras.preprocessing.image import load_img, array_to_img, img_to_array, ImageDataGenerator

datagen=ImageDataGenerator(rescale=1./255,
                           height_shift_range=0.2,
                           width_shift_range=0.2,
                           zoom_range=0.2,
                           shear_range=0.2,
                           
                           horizontal_flip=True,
                           rotation_range=40,
                           fill_mode='nearest')

In [38]:
# getting model

from tensorflow.keras.applications.vgg16 import VGG16

x= VGG16(include_top = False , weights = 'imagenet', input_shape = (126,55,3))

In [39]:
# Defining model and layers arrangement

import tensorflow
# from keras.models import Model
# from keras.layers import Flatten, Dense
from tensorflow.keras.callbacks import ModelCheckpoint,TensorBoard

for layer in x.layers:
    layer.trainable=False
    

y=tensorflow.keras.layers.Flatten()(x.output)
prediction=tensorflow.keras.layers.Dense(3, activation='softmax')(y)

model=tensorflow.keras.Model(inputs=x.input, outputs=prediction)
model.compile(loss='categorical_crossentropy',
              optimizer=tensorflow.keras.optimizers.Adam(learning_rate=0.001),metrics=['accuracy'])
# checkpoint
filepath="weights.{epoch:02d}-{val_loss:.2f}.hdf5"
checkpoint = ModelCheckpoint(filepath, monitor='val_acc', verbose=0, save_best_only=True, mode='max')


In [40]:
#create callback list

# Load the TensorBoard notebook extension
%load_ext tensorboard
import datetime,os
# from tensorflow.keras.callbacks import TensorBoard
# NAME = "Self_driving_car{}".format(int(time.time()))
logdir = os.path.join("logs", datetime.datetime.now().strftime("%Y%m%d-%H%M%S"))
tensorboard_callback = TensorBoard(logdir)



The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard


In [105]:
%reload_ext tensorboard

In [163]:
train=datagen.flow_from_directory('Trainingdatagame2', target_size=(126,55),batch_size=32, class_mode='categorical', shuffle = True)
test=datagen.flow_from_directory('Validationdatagame2', target_size=(126,55), batch_size=16, class_mode='categorical', shuffle = True)


Found 6480 images belonging to 3 classes.
Found 300 images belonging to 3 classes.


In [164]:
# from tensorflow.keras.models import load_model

# model = load_model('weights-improvement-02-0.33.hdf5')
model.fit(x=train, validation_data = test,epochs=8, steps_per_epoch=len(train), validation_steps = len(test), callbacks=[tensorboard_callback,checkpoint],verbose=1,sample_weight=None)

  ...
    to  
  ['...']
  ...
    to  
  ['...']
Train for 203 steps, validate for 19 steps
Epoch 1/8
203/203 [==============================] - 124s 610ms/step - loss: 0.5618 - accuracy: 0.7574 - val_loss: 0.7317 - val_accuracy: 0.6667
Epoch 2/8
203/203 [==============================] - 95s 467ms/step - loss: 0.5595 - accuracy: 0.7696 - val_loss: 0.7169 - val_accuracy: 0.7067
Epoch 3/8
203/203 [==============================] - 40s 197ms/step - loss: 0.5494 - accuracy: 0.7657 - val_loss: 0.7284 - val_accuracy: 0.6833
Epoch 4/8
203/203 [==============================] - 39s 191ms/step - loss: 0.5552 - accuracy: 0.7676 - val_loss: 0.7498 - val_accuracy: 0.6667
Epoch 5/8
203/203 [==============================] - 39s 193ms/step - loss: 0.5397 - accuracy: 0.7738 - val_loss: 0.7346 - val_accuracy: 0.6800
Epoch 6/8
203/203 [==============================] - 38s 189ms/step - loss: 0.5410 - accuracy: 0.7722 - val_loss: 0.7184 - val_accuracy: 0.6867
Epoch 7/8
203/203 [=======================

In [40]:
from tensorboard import notebook
notebook.list() 

Known TensorBoard instances:
  - port 6006: logdir logs (started 0:00:27 ago; pid 11368)


In [13]:
# collecting data from the NFS MW game

import numpy as np
import cv2
import time
from grabscreen import grab_screen
from getkeys import key_check
import pyautogui
import os
from tensorflow.keras.models import load_model

def keys_to_output(keys):
    output = [0,0,0]
    
    if 'A' in keys:
        output[0] = 1
        
    elif 'D' in keys:
        output[2] = 1
        
    else:
        output[1] = 1
        
    return output   

file_name = 'training_data134.npy'

if os.path.isfile(file_name):
    print('File exists, loading previous data!')
   
    training_data = list(np.load(file_name, allow_pickle = True))
    
else:
    print('File does not exist, starting fresh')
    training_data = []

def main():
    for i in list(range(5))[::-1]:
        print(i+1)
        time.sleep(1)
        
    last_time = time.time()


    count= 0
    
    while True:
            screen = grab_screen(region = (100,100+200,730,575))
            #cv2.imshow('screen', screen)
            screen = cv2.cvtColor(screen ,cv2.COLOR_BGR2RGB)
            screen = cv2.resize(screen , (126,55))
            keys = key_check()
            output = keys_to_output(keys)
            training_data.append([screen,output])
            
            print('Frame took {} seconds'.format(time.time() - last_time))
            last_time = time.time()
            
            if len(training_data) % 500 == 0:
                print(len(training_data))
                
                np.save(file_name, training_data)
                
                
             
#             count += 1
#             if 'A' in keys:
#                 cv2.imwrite("Training_data_game2\[1,0,0]\L_%d.jpg" %count, screen)
                                    

#             elif 'D' in keys:
#                 cv2.imwrite("Training_data_game2\[0,0,1]\R_%d.jpg"  %count, screen)
                
#             elif 'W' in keys:
#                 cv2.imwrite("Training_data_game2\[0,1,0]\S_%d.jpg" %count,screen)
                
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                         

        

main()


File does not exist, starting fresh
5
4
3
2
1
Frame took 0.06681537628173828 seconds
Frame took 0.01791667938232422 seconds
Frame took 0.016950130462646484 seconds
Frame took 0.015955448150634766 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.01599717140197754 seconds
Frame took 0.015916824340820312 seconds
Frame took 0.01670527458190918 seconds
Frame took 0.016955137252807617 seconds
Frame took 0.015958070755004883 seconds
Frame took 0.01595139503479004 seconds
Frame took 0.015957117080688477 seconds
Frame took 0.015961647033691406 seconds
Frame took 0.016750097274780273 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.015958309173583984 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.018950223922729492 seconds
Frame took 0.014960527420043945 seconds
Frame took 0.015963315963745117 seconds
Frame took 0.016947269439697266 seconds
Frame took 0.015995264053344727 seconds
Frame took 0.016954421997070312 seconds
Frame took 0.01599431037902832 seconds


Frame took 0.015958547592163086 seconds
Frame took 0.015962839126586914 seconds
Frame took 0.017950057983398438 seconds
Frame took 0.014000177383422852 seconds
Frame took 0.01695418357849121 seconds
Frame took 0.014960289001464844 seconds
Frame took 0.015957117080688477 seconds
Frame took 0.015958309173583984 seconds
Frame took 0.015958309173583984 seconds
Frame took 0.015999794006347656 seconds
Frame took 0.015957355499267578 seconds
Frame took 0.01595902442932129 seconds
Frame took 0.015958786010742188 seconds
Frame took 0.01595759391784668 seconds
Frame took 0.01596522331237793 seconds
Frame took 0.01694345474243164 seconds
Frame took 0.015958070755004883 seconds
Frame took 0.015964984893798828 seconds
Frame took 0.014949560165405273 seconds
Frame took 0.016954898834228516 seconds
Frame took 0.015959501266479492 seconds
Frame took 0.015958309173583984 seconds
Frame took 0.01695394515991211 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.01795339584350586 seconds
Frame t

Frame took 0.016955137252807617 seconds
Frame took 0.015958070755004883 seconds
Frame took 0.015955448150634766 seconds
Frame took 0.01596355438232422 seconds
Frame took 0.015955686569213867 seconds
Frame took 0.016002178192138672 seconds
Frame took 0.01595616340637207 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.0169522762298584 seconds
Frame took 0.015959501266479492 seconds
Frame took 0.015996932983398438 seconds
Frame took 0.01592111587524414 seconds
Frame took 0.016956090927124023 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.01695537567138672 seconds
Frame took 0.01595759391784668 seconds
Frame took 0.01496124267578125 seconds
Frame took 0.016954898834228516 seconds
Frame took 0.016954898834228516 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.01695537567138672 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.0159604549407959 seconds
Frame took 0.015958309173583984 seconds
Frame took 0.015921831130981445 seconds
Frame took 

Frame took 0.016952991485595703 seconds
Frame took 0.014958858489990234 seconds
Frame took 0.01695561408996582 seconds
Frame took 0.014960765838623047 seconds
Frame took 0.01595902442932129 seconds
Frame took 0.015958547592163086 seconds
Frame took 0.01496267318725586 seconds
Frame took 0.015010595321655273 seconds
Frame took 0.01690387725830078 seconds
Frame took 0.014995098114013672 seconds
Frame took 0.01791858673095703 seconds
Frame took 0.015955448150634766 seconds
Frame took 0.015996217727661133 seconds
Frame took 0.015958786010742188 seconds
Frame took 0.015956401824951172 seconds
Frame took 0.015958547592163086 seconds
Frame took 0.015956640243530273 seconds
Frame took 0.015998363494873047 seconds
Frame took 0.015984296798706055 seconds
Frame took 0.016929149627685547 seconds
Frame took 0.01695418357849121 seconds
Frame took 0.01595759391784668 seconds
Frame took 0.014959573745727539 seconds
Frame took 0.01795172691345215 seconds
Frame took 0.024933815002441406 seconds
Frame to

KeyboardInterrupt: 

In [14]:
# separating image data in to different categories and stores in working directory


# import numpy as np
import pandas as pd
from collections import Counter
from random import shuffle



# # train = list(np.load('training_data11.npy', allow_pickle = True))
# shuffle(traindata)
# count = 0
# for data in training_data:
#     count = count + 1
#     img = data[0]
#     choice = data[1]
    
#     if choice == [0,0,1]:
#         cv2.imwrite("Training_data_game2\[0,0,1]\Ri_%d.jpg" %count, img)
        
#     elif choice == [0,1,0]:
#         cv2.imwrite("Training_data_game2\[0,1,0]\St_%d.jpg" %count, img) 
        
#     elif choice == [1,0,0]:
#         cv2.imwrite("Training_data_game2\[1,0,0]\le_%d.jpg" %count, img) 
        
#     else:
#         print('no matches!!!!')

df = pd.DataFrame(training_data)
print(df.head())
print(Counter(df[1].apply(str)))


lefts = []
rights = []
forwards = []
shuffle(training_data)     

for data in training_data:
    img = data[0]
    choice = data[1]
    
    if choice == [1,0,0]:
        lefts.append([img,choice])
        
    elif choice == [0,1,0]:
        forwards.append([img,choice])
        
    elif choice == [0,0,1]:
        rights.append([img, choice])
    
    else:
        print('no matches!!!!')

# forwards = forwards[:len(lefts)][:len(rights)]
# lefts = lefts[:len(forwards)]
# rights = rights[:len(forwards)]

final_data = forwards + lefts + rights
shuffle(final_data)
print(len(final_data))

# shuffle(lefts)
# count1 = 0
# for data in lefts:
#     count1 = count1 + 1
#     img  = data[0]
#     cv2.imwrite("Trainingtemp\[1,0,0]\leftyys%d.jpg" %count1, img)

# shuffle(rights)    
# count2=0    
# for data in rights:
#     count2 = count2 + 1
#     img  = data[0]
#     cv2.imwrite("Trainingtemp\[0,0,1]\Rightyysto_%d.jpg" %count2, img)


shuffle(forwards)    
count3=0    

for data in forwards:
    count3 = count3 + 1
    img  = data[0]
    cv2.imwrite("Trainingtemp\[0,1,0]\rity_%d.jpg" %count3, img)    

                                                   0          1
0  [[[15, 18, 16], [16, 19, 17], [17, 20, 17], [1...  [0, 1, 0]
1  [[[15, 18, 16], [16, 19, 17], [17, 20, 17], [1...  [0, 1, 0]
2  [[[15, 18, 16], [16, 19, 17], [17, 20, 18], [1...  [0, 1, 0]
3  [[[15, 18, 16], [16, 19, 17], [17, 20, 18], [1...  [0, 1, 0]
4  [[[15, 18, 16], [16, 19, 17], [17, 20, 17], [1...  [0, 1, 0]
Counter({'[0, 1, 0]': 935, '[1, 0, 0]': 15})
950


In [15]:
print(forwards)

[[array([[[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       ...,

       [[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247]],

       [[238, 238, 238],
        [238, 238, 238],
        [238, 238, 238],
        ...,
        [247, 247, 247],
        [247, 247, 247],
        [247, 247, 247

In [3]:
# code for controlling the game and the output of DCNN/ model

from directkeys import PressKey, ReleaseKey, W,A,S,D
from tensorflow.keras.models import load_model
import cv2
import time
from grabscreen import grab_screen
import numpy as np
from getkeys import key_check


def right():
    PressKey(W)
    PressKey(D)
    ReleaseKey(S)
    
def left():
    PressKey(W)
    PressKey(A)
    ReleaseKey(D)
    
def forward():
    PressKey(W)
    ReleaseKey(A)
    ReleaseKey(D)

model = load_model('6th_good_.h5')




def drive():
       
       
            paused = False
            while True:
                if not paused:
                    screen = grab_screen(region = (100,100+200,730,575))
                    screen = cv2.cvtColor(screen , cv2.COLOR_BGR2RGB)
                    screen = cv2.resize(screen, (55,126))
                    screen4D = np.expand_dims(screen, axis = 0)
                    pred = model.predict(screen4D)
                    print(pred)


                    if pred[0][0] > 0.7:
                        right()

                    elif pred[0][1] > 0.5:
                        forward()

                    elif pred[0][2] > 0.7:
                        left()
                        
                    else: 
                        forward()
                        
                        

                keys = key_check()  
                if 'T' in keys:
                    if paused:
                        paused = False
                        time.sleep(1)
                    else:
                        paused = True
                        ReleaseKey(A)
                        ReleaseKey(W)
                        ReleaseKey(D)
                        time.sleep(1)
    
            
            
            
            
for t in list(range(5))[::-1]:
    print(t)
    time.sleep(1)

drive()    

4
3
2
1
0
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0.0000000e+00 1.0000000e+00 5.6508825e-37]]
[[0.0000000e+00 1.0000000e+00 1.3299208e-35]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[

[[4.2278467e-14 3.1621761e-30 1.0000000e+00]]
[[1.4668435e-17 5.0861301e-32 1.0000000e+00]]
[[9.2499264e-14 8.5197899e-29 1.0000000e+00]]
[[2.1606424e-21 9.0759859e-36 1.0000000e+00]]
[[9.029749e-20 0.000000e+00 1.000000e+00]]
[[1.1611696e-18 5.6845056e-36 1.0000000e+00]]
[[1.7525675e-13 1.4457959e-30 1.0000000e+00]]
[[1.6532587e-19 1.9630207e-37 1.0000000e+00]]
[[7.0267397e-10 6.8488026e-27 1.0000000e+00]]
[[4.0486458e-18 1.6780688e-36 1.0000000e+00]]
[[2.432562e-18 7.556876e-36 1.000000e+00]]
[[9.6434515e-19 2.6375056e-37 1.0000000e+00]]
[[3.3998099e-17 1.9662949e-38 1.0000000e+00]]
[[6.2512313e-16 1.8224006e-38 1.0000000e+00]]
[[1.02176416e-14 2.04442244e-36 1.00000000e+00]]
[[5.9534379e-17 2.8250817e-35 1.0000000e+00]]
[[2.5683174e-18 0.0000000e+00 1.0000000e+00]]
[[9.79247e-20 0.00000e+00 1.00000e+00]]
[[1.2751026e-15 0.0000000e+00 1.0000000e+00]]
[[3.757333e-19 0.000000e+00 1.000000e+00]]
[[9.406524e-19 0.000000e+00 1.000000e+00]]
[[6.2631675e-23 0.0000000e+00 1.0000000e+00]]
[[3

[[1.0000000e+00 1.0587842e-30 0.0000000e+00]]
[[1.0000000e+00 1.5234455e-23 0.0000000e+00]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 1.9038998e-25 0.0000000e+00]]
[[1.0000000e+00 3.8008477e-15 0.0000000e+00]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.000000e+00 7.738317e-23 0.000000e+00]]
[[1.0000000e+00 2.7825338e-21 0.0000000e+00]]
[[1.0000000e+00 2.1469544e-36 0.0000000e+00]]
[[1.0000000e+00 8.2421985e-32 0.0000000e+00]]
[[1. 0. 0.]]
[[1.0000000e+00 1.4410638e-33 0.0000000e+00]]
[[1.0000000e+00 4.2471477e-29 0.0000000e+00]]
[[1.000000e+00 6.668743e-28 0.000000e+00]]
[[1.0000000e+00 2.4256858e-26 0.0000000e+00]]
[[1.000000e+00 3.587035e-20 0.000000e+00]]
[[1.00000e+00 2.09796e-25 0.00000e+00]]
[[1. 0. 0.]]
[[1.0000000e+00 3.9746095e-34 0.0000000e+00]]
[[1.000000e+00 5.010608e-37 0.000000e+00]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 1.8489899e-37 0.0000000e+00]]
[[1.00000e+00 7.64757e-33 0.00000e+00]]
[

[[1.0000000e+00 3.8860477e-35 0.0000000e+00]]
[[0.4777864 0.5222136 0.       ]]
[[1.000000e+00 7.289795e-14 0.000000e+00]]
[[1. 0. 0.]]
[[1.0000000e+00 7.7817455e-30 0.0000000e+00]]
[[1.0000000e+00 1.3250953e-34 0.0000000e+00]]
[[1.000000e+00 0.000000e+00 8.704766e-32]]
[[1.0000000e+00 1.2604822e-31 5.6733787e-18]]
[[1.000000e+00 0.000000e+00 3.571429e-20]]
[[1.0000000e+00 1.6138895e-19 1.9825974e-27]]
[[1.518085e-23 1.000000e+00 0.000000e+00]]
[[1.000000e+00 5.919283e-19 0.000000e+00]]
[[9.9999893e-01 4.7460997e-36 1.1109280e-06]]
[[1.0000000e+00 1.3089313e-37 8.5267362e-13]]
[[1.000000e+00 0.000000e+00 3.420438e-19]]
[[9.9082363e-01 4.1995835e-34 9.1763483e-03]]
[[1. 0. 0.]]
[[4.6916740e-04 5.5953735e-09 9.9953079e-01]]
[[0.00162609 0.99837387 0.        ]]
[[3.906069e-19 1.000000e+00 0.000000e+00]]
[[1.0765916e-28 1.0000000e+00 0.0000000e+00]]
[[1.2605648e-11 1.0000000e+00 0.0000000e+00]]
[[1.6940472e-34 1.0000000e+00 0.0000000e+00]]
[[0.17877156 0.82122844 0.        ]]
[[9.9999833e-

[[9.9999976e-01 0.0000000e+00 2.8872395e-07]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[4.0471502e-17 1.0000000e+00 0.0000000e+00]]
[[0. 1. 0.]]
[[8.813215e-34 1.000000e+00 0.000000e+00]]
[[9.046326e-29 1.000000e+00 0.000000e+00]]
[[0. 1. 0.]]
[[0.9984308  0.00156914 0.        ]]
[[0. 1. 0.]]
[[0.03048187 0.9695181  0.        ]]
[[1.0000000e+00 4.6664997e-22 0.0000000e+00]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 3.4142268e-15]]
[[9.9994135e-01 0.0000000e+00 5.8669597e-05]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[5.786983e-12 0.000000e+00 1.000000e+00]]
[[0. 0. 1.]]
[[4.138462e-34 0.000000e+00 1.000000e+00]]
[[1.0000000e+00 0.0000000e+00 6.0921773e-10]]
[[1.0000000e+00 0.0000000e+00 1.2195936e-21]]
[[1.5214959e-13 0.0000000e+00 1.0000000e+00]]
[[0.9985813  0.         0.00141876]]
[[1.00000e+00 0.00000e+00 6.54525e-20]]
[[1.000000e+00 0.000000

[[1.0000000e+00 1.2932924e-29 0.0000000e+00]]
[[1.0000000e+00 7.3594884e-38 0.0000000e+00]]
[[1.0000000e+00 1.4703927e-28 0.0000000e+00]]
[[1.0000000e+00 1.7282159e-28 0.0000000e+00]]
[[1. 0. 0.]]
[[1.0000000e+00 5.7446887e-30 0.0000000e+00]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.000000e+00 7.686604e-36 0.000000e+00]]
[[8.8734251e-01 1.1265748e-01 1.2207325e-34]]
[[1.0000000e+00 1.8365684e-11 0.0000000e+00]]
[[1.0000000e+00 1.6781936e-25 0.0000000e+00]]
[[1.000000e+00 4.991789e-10 0.000000e+00]]
[[4.134904e-15 1.000000e+00 0.000000e+00]]
[[1. 0. 0.]]
[[1.000000e+00 6.879025e-10 0.000000e+00]]
[[1.0000000e+00 6.0529715e-36 0.0000000e+00]]
[[1.0000000e+00 3.1845595e-22 0.0000000e+00]]
[[1.0000000e+00 2.8863236e-20 0.0000000e+00]]
[[9.585761e-11 1.000000e+00 0.000000e+00]]
[[1.0000000e+00 1.1531566e-20 0.0000000e+00]]
[[6.3223403e-15 2.5141338e-30 1.0000000e+00]]
[[4.2524077e-18 0.0000000e+00 1.0000000e+00]]
[[7.822424e-13 0.000000e+00 1.000000e+00]]
[[2.267

[[1. 0. 0.]]
[[1.00000000e+00 0.00000000e+00 1.25262915e-26]]
[[9.9999344e-01 0.0000000e+00 6.5195127e-06]]
[[1.000000e+00 0.000000e+00 5.578861e-26]]
[[0.00834537 0.         0.99165463]]
[[1.000000e+00 0.000000e+00 6.041382e-24]]
[[0.78515357 0.         0.21484645]]
[[1.0000000e+00 0.0000000e+00 2.6222807e-19]]
[[9.9997628e-01 0.0000000e+00 2.3677967e-05]]
[[1.0000000e+00 0.0000000e+00 3.5538806e-29]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 1.2345162e-28]]
[[1.0000000e+00 0.0000000e+00 2.8572419e-25]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.00000e+00 0.00000e+00 8.76699e-38]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 6.220412e-28]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 5.441596e-38]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 6.413191e-29]]
[[1.0000000e+00 0.0000000e+00 2.9305695e-27]]
[[1.0000000e+00 0.0000000e+00 1.9818256e-20]]
[[1.00000e+00 0.00000e+00 3.70668e-19]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.00

[[0. 1. 0.]]
[[7.6940175e-08 9.9999988e-01 3.9457379e-35]]
[[1.000000e+00 5.797213e-23 0.000000e+00]]
[[1.000000e+00 2.573031e-28 0.000000e+00]]
[[1.0000000e+00 1.8275155e-10 0.0000000e+00]]
[[9.999958e-01 4.167861e-06 0.000000e+00]]
[[1.4523699e-13 1.0000000e+00 0.0000000e+00]]
[[0.9979633  0.00203674 0.        ]]
[[1.0000000e+00 6.2638374e-30 0.0000000e+00]]
[[3.7264407e-28 1.0000000e+00 0.0000000e+00]]
[[3.9909564e-12 1.0000000e+00 0.0000000e+00]]
[[1.000000e+00 7.249067e-23 0.000000e+00]]
[[5.7529054e-10 1.0000000e+00 0.0000000e+00]]
[[8.8915744e-23 1.0000000e+00 0.0000000e+00]]
[[4.8225147e-15 1.0000000e+00 4.5122733e-31]]
[[0. 1. 0.]]
[[1.1274297e-25 1.0000000e+00 4.1961127e-37]]
[[2.5905197e-06 9.9999738e-01 0.0000000e+00]]
[[9.9526250e-01 4.7374633e-03 1.6781092e-35]]
[[1.00000000e+00 1.28125075e-08 0.00000000e+00]]
[[8.106264e-28 1.000000e+00 0.000000e+00]]
[[0.00111162 0.99888843 0.        ]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0

[[9.999999e-01 0.000000e+00 6.191639e-08]]
[[1.000000e+00 0.000000e+00 9.421046e-16]]
[[1.0000000e+00 0.0000000e+00 1.0120687e-24]]
[[1.0000000e+00 0.0000000e+00 1.3344514e-16]]
[[1.0285634e-24 0.0000000e+00 1.0000000e+00]]
[[1.0000000e+00 0.0000000e+00 2.4420693e-10]]
[[2.0511619e-08 0.0000000e+00 1.0000000e+00]]
[[9.999604e-01 0.000000e+00 3.963549e-05]]
[[0. 0. 1.]]
[[1.0000000e+00 0.0000000e+00 7.3088974e-10]]
[[1.0000000e+00 0.0000000e+00 1.7482576e-24]]
[[9.999980e-01 0.000000e+00 2.046613e-06]]
[[1.000000e+00 0.000000e+00 7.404368e-10]]
[[1.0000000e+00 0.0000000e+00 2.0973067e-30]]
[[1.0000000e+00 0.0000000e+00 1.1649337e-30]]
[[1.000000e+00 0.000000e+00 2.251811e-12]]
[[1.0000000e+00 0.0000000e+00 5.0890863e-22]]
[[0. 0. 1.]]
[[1.3960463e-06 0.0000000e+00 9.9999857e-01]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 5.6616357e-12]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 

[[1.3668518e-04 0.0000000e+00 9.9986327e-01]]
[[0.00511094 0.         0.9948891 ]]
[[0.0014778 0.        0.9985222]]
[[0.03442491 0.         0.96557504]]
[[0.01548054 0.         0.9845195 ]]
[[8.36072e-04 0.00000e+00 9.99164e-01]]
[[2.2149009e-04 0.0000000e+00 9.9977857e-01]]
[[1.5082951e-04 0.0000000e+00 9.9984920e-01]]
[[2.2498281e-04 0.0000000e+00 9.9977499e-01]]
[[9.0173316e-06 0.0000000e+00 9.9999094e-01]]
[[6.0521916e-07 0.0000000e+00 9.9999940e-01]]
[[3.866442e-06 0.000000e+00 9.999962e-01]]
[[1.7138811e-07 0.0000000e+00 9.9999988e-01]]
[[3.573908e-06 0.000000e+00 9.999964e-01]]
[[1.1346287e-04 0.0000000e+00 9.9988651e-01]]
[[6.2309398e-04 0.0000000e+00 9.9937695e-01]]
[[0.7769346  0.         0.22306535]]
[[0.9983835  0.         0.00161643]]
[[9.990783e-01 0.000000e+00 9.216760e-04]]
[[0.9772085  0.         0.02279148]]
[[4.412216e-06 0.000000e+00 9.999956e-01]]
[[9.9999845e-01 0.0000000e+00 1.5003008e-06]]
[[0.8921556  0.         0.10784438]]
[[0.00372677 0.         0.9962733 ]

[[9.9999988e-01 0.0000000e+00 6.0364776e-08]]
[[1.000000e+00 0.000000e+00 5.838813e-35]]
[[1.0000000e+00 0.0000000e+00 4.9131725e-28]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 3.0316065e-30]]
[[1.0000000e+00 0.0000000e+00 1.6404526e-15]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 3.128252e-26]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 2.2427901e-29]]
[[1.0000000e+00 0.0000000e+00 5.0591063e-36]]
[[1.0000000e+00 0.0000000e+00 2.8366642e-31]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 1.4750535e-16]]
[[1.00000000e+00 0.00000000e+00 1.40315315e-08]]
[[9.999628e-01 0.000000e+00 3.715735e-05]]
[[1.0000000e+00 0.0000000e+00 2.6161923e-29]]
[[1.8694377e-10 0.0000000e+00 1.0000000e+00]]
[[0.63511586 0.         0.36488408]]
[[0.01526619 0.         0.9847339 ]]
[[0.961412   0.         0.03858807]]
[[3.7709874e-27 0.0000000e+00 1.0000000e+00]]
[[3.3943625e-27 0.0000000e+00 1.0000000e+00]]
[[3.893955e-36 0.000000e+00 1.000000e+00]]
[[0. 0. 1.]]
[[1.3198011e-30 0.0000000e+00 1.000000

[[0.0000000e+00 1.0000000e+00 7.7792854e-29]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[5.71446949e-27 1.00000000e+00 1.12050725e-29]]
[[0.0000000e+00 1.0000000e+00 1.1301771e-32]]
[[0.0000000e+00 1.0000000e+00 2.0291912e-31]]
[[2.690140e-23 1.000000e+00 1.180409e-34]]
[[4.1095292e-20 1.0000000e+00 3.5317706e-29]]
[[8.1876614e-08 9.9999988e-01 5.8714596e-30]]
[[2.3673420e-28 1.0000000e+00 2.4134727e-35]]
[[5.331596e-34 1.000000e+00 0.000000e+00]]
[[2.5456718e-23 1.0000000e+00 0.0000000e+00]]
[[1.0249960e-30 1.0000000e+00 5.5219586e-30]]
[[2.8581839e-37 1.0000000e+00 2.3479762e-30]]
[[6.4821095e-36 1.0000000e+00 0.0000000e+00]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[2.0505255e-18 1.0000000e+00 2.0173188e-33]]
[[3.9729653e-15 1.0000000e+00 6.4300070e-18]]
[[2.0590396e-24 1.0000000e+00 3.4041608e-15]]
[[2.7151215e-16 8.6500275e-01 1.3499728e-01]]
[[6.8206116e-26 3.0283653e-04 9.9969721e-01]]
[[1.9735409e-36 1.0000000e+00 8.1071570e-14]]
[[0.0000000e+00 1.0000000e+00 1.4621705e-28]]
[[1.7563234e-34 1.0000000e+00 5

[[0.0000000e+00 1.0000000e+00 2.4009064e-16]]
[[1.0000000e+00 8.4163071e-18 4.3991147e-15]]
[[5.9685321e-26 1.0339779e-14 1.0000000e+00]]
[[9.9998868e-01 3.6028982e-07 1.0921160e-05]]
[[1.0000000e+00 0.0000000e+00 1.8786022e-29]]
[[1.0000000e+00 5.5338291e-38 2.3667383e-27]]
[[1.5037666e-10 2.4681675e-24 1.0000000e+00]]
[[1.19233185e-30 0.00000000e+00 1.00000000e+00]]
[[1.0000000e+00 6.1107213e-12 0.0000000e+00]]
[[8.4451669e-01 1.5548326e-01 7.7880929e-25]]
[[1.0000000e+00 2.5630727e-17 0.0000000e+00]]
[[1. 0. 0.]]
[[1.000000e+00 6.885632e-35 0.000000e+00]]
[[1.0000000e+00 8.2012779e-15 1.6177151e-29]]
[[1.000000e+00 5.179152e-31 0.000000e+00]]
[[1. 0. 0.]]
[[9.999987e-01 1.358923e-06 0.000000e+00]]
[[1.0000000e+00 1.1083653e-15 0.0000000e+00]]
[[5.0532254e-09 1.0000000e+00 0.0000000e+00]]
[[1.0000000e+00 1.0955928e-33 0.0000000e+00]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.1816571e-04 9.9988186e-01 3.3399763e-29]]
[[9.9894601e-01 1.0540135e-03 6.1473242e-27]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 

[[1.00000000e+00 0.00000000e+00 1.18080656e-32]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 9.878911e-21]]
[[1.00000e+00 0.00000e+00 3.87762e-36]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 5.7093784e-32]]
[[1.0000000e+00 0.0000000e+00 8.2900207e-35]]
[[1.0000000e+00 1.9702594e-38 1.5011205e-30]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[0. 1. 0.]]
[[2.4738376e-20 1.0000000e+00 0.0000000e+00]]
[[9.287628e-23 1.000000e+00 0.000000e+00]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0.0000000e+00 1.0000000e+00 1.9503977e-38]]
[[0. 1. 0.]]
[[0. 1. 0.]]
[[0.         0.03765847 0.96234155]]
[[0.0000000e+00 9.9997306e-01 2.6940226e-05]]
[[6.3164073e-16 1.0000000e+00 2.7067459e-29]]
[[6.1469477e-16 1.0000000e+00 2.0341782e-20]]
[[2.5233893e-28 1.0000000e+00 1.3548965e-32]]
[[0.         0.00993138 0.9900686 ]]
[[0.000000e+00 1.000000e+00 4.368311e-38]]
[[0.0000000e+00 1.0000000e+00 4.0797766e-26]]
[[0. 1. 0.]]
[[0.0000000e+00 1.0000000e+00 7.4362025e-20]]
[[6.848

[[1.0000000e+00 0.0000000e+00 3.2049997e-13]]
[[1.0000000e+00 0.0000000e+00 1.8582973e-20]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[0. 0. 1.]]
[[0. 0. 1.]]
[[1.0000000e+00 0.0000000e+00 1.1130664e-26]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 2.461683e-36]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[1.5605775e-17 0.0000000e+00 1.0000000e+00]]
[[4.273384e-11 0.000000e+00 1.000000e+00]]
[[0. 0. 1.]]
[[1. 0. 0.]]
[[9.999994e-01 0.000000e+00 5.430035e-07]]
[[2.350504e-22 0.000000e+00 1.000000e+00]]
[[0.9743079 0.        0.0256921]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 1.4369205e-24]]
[[1.0000000e+00 0.0000000e+00 7.4878674e-35]]
[[9.9999988e-01 0.0000000e+00 1.0733552e-07]]
[[1. 0. 0.]]
[[1.000000e+00 0.000000e+00 6.483176e-20]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 4.9987533e-29]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 1.1218134e-11]]
[[1.000000e+00 0.000000e+00 8.636931e-31]]
[[1. 0. 0.]]
[[1.0000000e+00 0.0000000e+00 2.3134037e-27]]
[[1. 0. 0.]]
[

KeyboardInterrupt: 

In [160]:
model.save('5th_good_.h5')